spring:
  application:
    name: Railway
  profiles:
    active: mysql
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
railway:
  times:
    - "00:00"
    - "05:30"
    - "06:00"
    - "06:30"
    - "06:45"
    - "07:00"
    - "07:15"
    - "07:30"
    - "07:45"
    - "08:00"
    - "08:15"
    - "08:30"
    - "09:00"
    - "09:30"
    - "10:00"
    - "10:30"
    - "11:00"
    - "11:30"
    - "11:45"
    - "12:00"
    - "12:15"
    - "12:30"
    - "12:45"
    - "13:15"
    - "13:30"
    - "14:00"
    - "14:30"
    - "15:00"
    - "15:30"
    - "16:00"
    - "16:15"
    - "16:30"
    - "16:45"
    - "17:00"
    - "17:15"
    - "17:30"
    - "17:45"
    - "18:00"
    - "18:15"
    - "18:30"
    - "18:45"
    - "19:00"
    - "19:30"
    - "20:00"
    - "20:30"
    - "21:00"
    - "21:30"
    - "22:00"
    - "22:30"
    - "23:00"
    - "23:30"