spring:
    datasource:
      url: jdbc:mysql://localhost:3306/railway
      username: root
      password:
    jpa:
      hibernate.ddl-auto: create-drop
      generate-ddl: true
      show-sql: false
